console.log(2>=1); //BASIC AS IN EVERY OTHER LANGUAGE

console.log("2">1)
console.log("1"<2)
//CONFUSING --->  SO IT IS ADVISED TO NOT COMPARE TWO DIFFERENT DATATYPE, FIRST CONVERT THEM INTO SAME


/*
THE EQUALITY OPERATOR(CASE1) AND COMPARSION OPERATOR(CASE2 AND 3) WORKS DIFFERENTLY
COMPARISON OPERATOR CONVERTS THE NULL INTO NUMERIC VALUE (0) 
*/

//NULL VALUE CHECK
console.log(null==0);    //FALSE
console.log(null>0);   //FALSE
console.log(null>=0);   //TRUE
 

// STRICT CHECK (===) ---> CHECK THE VALUE AS WELL AS DATATYPE
console.log("2"===2);

